### ISSUE TITLE
Feedback HW6

### ISSUE THREAD

**Issue by VladFomenko** [bohdanshvec/RubyHW#10]
I don't see authors controller and its routes.
So, I can't check connection author-article-comments or another connection with author.
Also I don't create none author.

I cannot create an article, because, I don't have any authors.
I cannot create an article because, I don't have any authors.

You need to create routes and controllers for author and update your action in article and comments.

As for the default value. I think you only need to create once in your migration. Not in the model. But I could be wrong. 

`enum :status, %i[unpublished published], default: :unpublished`
`change_column_default :comments, :status, from: nil, to: 0`

And you need to improve your codestyle(no comments, empty line, etc). Use command Rubocop, it will help to you in next HW.

**Comment by bohdanshvec** [comment]
Fixed a bug, Articles created and updated.
I use Rubocop it all the time.
The HW rest is done according to the task.

**Comment by VladFomenko** [comment]
Now it works, but before starting the test, you need to create an author. 
Great job!
