### ISSUE TITLE
Feedback for HW2 task2

### ISSUE THREAD

**Issue by MaksHostroushko** [bohdanshvec/RubyHW#4]
1. Please, remove all useless empty lines in your file
See [this style guide](https://github.com/rubocop/ruby-style-guide) as a reference

2. Try to avoid using `the` in your methods(Like`the_end`)

3. Don't use empty `case`. Better to use if/elsif/else. Or `case` with a condition

4. Don't use `if/eslif` without `else`. It's a bad way. Always try to add `else` option

5. 10.times { |x| print x; sleep 0.5 }
Try to don't split your code by `;`.
Could be better if you will open block and add a couple of lines with code
```
10.times do |x|
  print x
  sleep 0.5
end
```
6. `10.times { |x| print x.to_s + " #{ ["):", "(:", "[:", "]:", "{:", "};"].sample }"; sleep 0.5 }`
Looks really unreadable
Please, refactor it

7. `z = rand(50)`
Please, don't use one letter as the name of a variable
The name of a variable should describe the value of this variable

8. Refactor all spaces in your code(according to style guide from 1 point)

**Comment by bohdanshvec** [comment]
Yes, thenk you, checked rubocop.
