### ISSUE TITLE
Feedback HW5

### ISSUE THREAD

**Issue by alinajuly** [bohdanshvec/RubyHW#8]
Виконано до вимог завдання. 

Як побажання, зробити для методу update можливість змінювати не тільки body, а й title

https://github.com/bohdanshvec/RubyHW/blob/4e114cfa24eb163d6dea065777c5ec257d77449f/HW5/stories/app/controllers/api/v1/articles_controller.rb#L23

**Comment by bohdanshvec** [comment]
Thanks for feetback.
